# Generated by Django 3.1.2 on 2021-07-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210714_0709'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.CharField(choices=[('maths', 'MATHS'), ('science', 'science'), ('history', 'history'), ('geography', 'geography'), ('english', 'english')], max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject')},
        ),
    ]
